name: 4dPocket
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - pip=23.3.1
  - pytorch=2.1.0
  - pytorch3d
  - fvcore
  - iopath
  - torchvision
  - pip:
    - numpy
    - scipy